name: install_all_ubuntu_deps
runs:
  using: composite
  steps:
  - name: Install dependencies
    run: |-
      echo "Install dependencies"
      sudo apt-get update || true
      #TODO: apt-get steps
    shell: bash
  - name: Install cuda
    run: |-
      echo "Install cuda"
      wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
      sudo dpkg -i cuda-keyring_1.1-1_all.deb
      sudo apt-get update
      sudo apt-get -y install cuda-toolkit-12-3
      touch ~/cuda_installed
      if command -v nvidia-smi; then nvidia-smi; fi
    shell: bash
  - name: Setup miniconda
    uses: conda-incubator/setup-miniconda@v3.0.1
    with:
      miniconda-version: "latest"
      python-version: "3.9"
      activate-environment: "habitat"
  - name: Install conda and dependencies
    run: |-
      echo "Install conda and dependencies"
      conda install -y pytorch==1.12.1 torchvision==0.13.1 -c pytorch -c nvidia
      conda install -y -c conda-forge ninja numpy pytest pytest-cov ccache hypothesis pytest-mock
      pip install pytest-sugar pytest-xdist pytest-benchmark opencv-python cython mock
    shell: bash -el {0}
  - name: Validate Pytorch Installation
    run: |-
      echo "Validate Pytorch Installation"
      # Check that pytorch is installed with CUDA.
      python -c 'import torch; torch.cuda.set_device(0)'
    shell: bash -el {0}
