[tool.isort]
skip_glob = [ "*/deps/*", "*/build/*", "*/obselete/*",]
profile = "black"

[tool.black]
exclude = "(\n  /(\n      \\.eggs         # exclude a few common directories in the\n    | \\.git          # root of the project\n    | \\.hg\n    | \\.mypy_cache\n    | \\.tox\n    | \\.venv\n    | _build\n    | buck-out\n    | ^examples/tutorials/colabs\n    | ^examples/tutorials/nb_python\n    | build\n    | dist\n    | obselete\n    | deps\n  )/\n)\n"
