[tool.black]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | ^examples/tutorials/colabs
    | ^examples/tutorials/nb_python
    | build
    | dist
    | obselete
    | deps
  )/
)
'''

[tool.isort]
skip_glob = ["*/deps/*", "*/build/*", "*/obselete/*"]
profile = 'black'
treat_comments_as_code = "# %%"

[tool.pytest.ini_options]
markers = [
    "sim_benchmarks: marks tests which use pytest-benchmark for perf tracking of simulator features so they can be easily run together.)",
]
