{% set headless_build_variant = environ.get('HABITAT_HEADLESS_VARIANT', 'display') %}
{% set bullet_build_variant = environ.get('HABITAT_BULLET_VARIANT', 'nobullet') %}


package:
  name: habitat-sim
  version: "{{ environ.get('VERSION') }}"

source:
  path: "{{ environ.get('HSIM_SOURCE_PATH') }}"


requirements:
  build:
    - cmake
    - ninja
    - pkg-config # [unix]
    - {{ cdt('libpng-devel') }} # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]

  host:
    - python x.x
    - pip
    - setuptools
    - attrs>=19.1.0
    - smmap<4.0,>=3.0.1
    - numba
    - numpy>=1.13
    - gitpython
    - quaternion
    - pillow
    - scipy>=1.3.0
    - tqdm
    - imageio
    - imageio-ffmpeg
    - matplotlib
    - libglu                             # [linux]
    - libxcb                             # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxau                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libxi                         # [linux]
    - xorg-libxrandr         # [linux]
    - xorg-libxinerama       # [linux]
    - xorg-libxcursor        # [linux]

  run:
    - habitat-sim-mutex 1.0 {{ headless_build_variant }}_{{ bullet_build_variant }}
    - python x.x
    - smmap<4.0,>=3.0.1
    - gitpython
    - attrs>=19.1.0
    - numba
    - numpy>=1.13
    - quaternion
    - pillow
    - scipy>=1.3.0
    - tqdm
    - imageio
    - imageio-ffmpeg
    - matplotlib
    - libxcb                             # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxau                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libxi                         # [linux]
    - xorg-libxrandr         # [linux]
    - xorg-libxcursor        # [linux]
    {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT', '') }}

  run_constrained:
    - headless {% if headless_build_variant == "display" %} <0 {% endif %}
    - withbullet {% if bullet_build_variant == "nobullet" %} <0 {% endif %}

build:
  string: "{{ environ.get('HSIM_BUILD_STRING') }}"
  binary_relocation: True
  detect_binary_files_with_prefix: False
  script_env:
    - HEADLESS
    - WITH_CUDA
    - WITH_BULLET
    - CUDA_VER

about:
  home: https://aihabitat.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flexible, high-performance 3D simulator for Embodied AI research.
