# This action installs required Ubuntu NVIDIA dependencies.
# It assumes that `nvidia-smi` is available on the system.
name: "Install GPU Dependencies"
runs:
  using: composite
  steps:
  - name: Install GPU Dependencies
    shell: bash
    run: |
      NVIDIA_SMI_OUTPUT=$(nvidia-smi)
      DRIVER_VERSION=$(echo "$NVIDIA_SMI_OUTPUT" | grep -oP 'Driver Version:\s+\K[\d.]+')
      MAJOR_VERSION=$(echo "$NVIDIA_SMI_OUTPUT" | grep -oP 'Driver Version:\s+\K\d+')
      UBUNTU_PACKAGE_SUFFIX="${MAJOR_VERSION}=${DRIVER_VERSION}-0ubuntu1"
      sudo apt-get update
      sudo apt-get install -y libnvidia-common-${DRIVER_VERSION}
      sudo apt-get install -y libnvidia-gl-${DRIVER_VERSION}
